export const MOCK_DONOR_REQUESTS = [
  {
    id: 'req-101',
    patientName: 'Emergency Recipient #402',
    hospitalName: 'City Care Hospital',
    city: 'Sector 14, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    distanceKm: 2.8,
    requiredDate: 'Today, Immediate',
    additionalNotes: 'Urgent requirement for surgery in Trauma Center.',
    createdAt: '15 mins ago',
    status: 'Active',
  },
  {
    id: 'req-102',
    patientName: 'Emergency Recipient #389',
    hospitalName: 'St. Jude Medical Center',
    city: 'East Wing Campus',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'High',
    distanceKm: 5.2,
    requiredDate: 'Tomorrow Morning',
    additionalNotes: 'Dengue patient with dropping platelet count.',
    createdAt: '1 hour ago',
    status: 'Active',
  },
  {
    id: 'req-103',
    patientName: 'Recipient #274',
    hospitalName: 'Metro General Hospital',
    city: 'Central District',
    bloodGroup: 'O-',
    unitsNeeded: 3,
    urgency: 'Normal',
    distanceKm: 8.1,
    requiredDate: 'In 2 days',
    additionalNotes: 'Scheduled procedure blood standby.',
    createdAt: '3 hours ago',
    status: 'Active',
  },
];

export const MOCK_DONOR_STATS = {
  nearbyActiveCount: 3,
  acceptedCount: 1,
  completedDonations: 4,
  responseRate: '94%',
};

export const MOCK_DONOR_HISTORY = [
  {
    id: 'req-201',
    hospitalName: 'St. Mary Trauma Hospital',
    city: 'North Sector, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    status: 'Completed',
    responseDate: '12 Sep 2026',
    notes: '2 units donated successfully at Trauma ICU.',
  },
  {
    id: 'req-198',
    hospitalName: 'City Care Hospital',
    city: 'Sector 14, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'High',
    status: 'Accepted',
    responseDate: '25 Sep 2026',
    notes: 'Accepted. Hospital coordinator contact active.',
  },
  {
    id: 'req-185',
    hospitalName: 'Apex Health Institute',
    city: 'West District',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Normal',
    status: 'Declined',
    responseDate: '02 Aug 2026',
    notes: 'Declined due to travel unavailability.',
  },
  {
    id: 'req-172',
    hospitalName: 'Metro General Hospital',
    city: 'Central District',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'Emergency',
    status: 'Cancelled',
    responseDate: '15 Jul 2026',
    notes: 'Request cancelled by recipient (fulfilled locally).',
  },
];

export const MOCK_RECIPIENT_REQUESTS = [
  {
    id: 'req-301',
    hospitalName: 'City General Hospital',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    status: 'Donor Accepted',
    donorResponsesCount: 2,
    acceptedDonors: [
      { name: 'David Miller', phone: '+1 (555) 123-9876', bloodGroup: 'A+', distanceKm: 2.4 },
      { name: 'Elena Rostova', phone: '+1 (555) 876-5432', bloodGroup: 'A+', distanceKm: 4.1 },
    ],
    requiredDate: 'Today, Immediate',
    createdAt: '25 mins ago',
  },
  {
    id: 'req-302',
    hospitalName: 'Memorial Trauma Center',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 1,
    urgency: 'High',
    status: 'Active',
    donorResponsesCount: 0,
    acceptedDonors: [],
    requiredDate: 'Tomorrow Morning',
    createdAt: '2 hours ago',
  },
];

export const MOCK_RECIPIENT_STATS = {
  totalRequests: 4,
  activeRequests: 2,
  donorsResponded: 2,
  fulfilledCount: 2,
};

export const MOCK_RECIPIENT_LOCATION = {
  lat: 40.7128,
  lng: -74.006,
  address: 'New York Central Search Center',
};

export const MOCK_SEARCHABLE_DONORS = [
  {
    id: 'donor-1',
    name: 'David M.',
    bloodGroup: 'A+',
    distanceKm: 2.4,
    city: 'New York, Sector 14',
    isAvailable: true,
    lastActive: '5 mins ago',
    donationsCompleted: 6,
    responseRate: '98%',
    lat: 40.725,
    lng: -73.998,
  },
  {
    id: 'donor-2',
    name: 'Elena R.',
    bloodGroup: 'A+',
    distanceKm: 4.1,
    city: 'New York, East Wing',
    isAvailable: true,
    lastActive: '12 mins ago',
    donationsCompleted: 4,
    responseRate: '92%',
    lat: 40.738,
    lng: -73.985,
  },
  {
    id: 'donor-3',
    name: 'Marcus Vance',
    bloodGroup: 'O-',
    distanceKm: 1.8,
    city: 'New York, Downtown',
    isAvailable: true,
    lastActive: 'Just now',
    donationsCompleted: 12,
    responseRate: '100%',
    lat: 40.708,
    lng: -74.012,
  },
  {
    id: 'donor-4',
    name: 'Sarah K.',
    bloodGroup: 'O+',
    distanceKm: 5.8,
    city: 'New York, Midtown',
    isAvailable: true,
    lastActive: '45 mins ago',
    donationsCompleted: 3,
    responseRate: '88%',
    lat: 40.752,
    lng: -73.977,
  },
  {
    id: 'donor-5',
    name: 'Robert T.',
    bloodGroup: 'B+',
    distanceKm: 6.9,
    city: 'New York, West District',
    isAvailable: true,
    lastActive: '1 hour ago',
    donationsCompleted: 5,
    responseRate: '95%',
    lat: 40.735,
    lng: -74.032,
  },
  {
    id: 'donor-6',
    name: 'Anita Patel',
    bloodGroup: 'AB+',
    distanceKm: 8.4,
    city: 'New York, North Campus',
    isAvailable: false,
    lastActive: '3 hours ago',
    donationsCompleted: 2,
    responseRate: '80%',
    lat: 40.768,
    lng: -73.962,
  },
  {
    id: 'donor-7',
    name: 'Jonathan L.',
    bloodGroup: 'A-',
    distanceKm: 12.1,
    city: 'New York, Queens Area',
    isAvailable: true,
    lastActive: '20 mins ago',
    donationsCompleted: 7,
    responseRate: '96%',
    lat: 40.748,
    lng: -73.912,
  },
  {
    id: 'donor-8',
    name: 'Sophia W.',
    bloodGroup: 'B-',
    distanceKm: 16.5,
    city: 'New York, Brooklyn Sector',
    isAvailable: true,
    lastActive: '2 hours ago',
    donationsCompleted: 1,
    responseRate: '90%',
    lat: 40.672,
    lng: -73.952,
  },
];

export const MOCK_ADMIN_STATS = {
  totalDonors: 142,
  totalRecipients: 89,
  activeAvailableDonors: 94,
  activeRequests: 8,
  emergencyRequests: 3,
  fulfilledRequests: 56,
};

export const MOCK_ADMIN_ACTIVITY = [
  {
    id: 'act-1',
    user: 'System Admin',
    action: 'Verified Donor Account #donor-3 (Marcus Vance)',
    time: '10 mins ago',
    type: 'security',
  },
  {
    id: 'act-2',
    user: 'Recipient #rec-12',
    action: 'Issued Emergency Request #req-301 (A+)',
    time: '25 mins ago',
    type: 'request',
  },
  {
    id: 'act-3',
    user: 'Donor #donor-1',
    action: 'Accepted Emergency Request #req-301',
    time: '20 mins ago',
    type: 'donor',
  },
  {
    id: 'act-4',
    user: 'System Admin',
    action: 'Logged System Audit Trail #audit-994',
    time: '1 hour ago',
    type: 'audit',
  },
];