export const MOCK_DONOR_REQUESTS = [
  {
    id: 'req-101',
    patientName: 'Emergency Recipient #402',
    hospitalName: 'City Care Hospital',
    city: 'Sector 14, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    distanceKm: 2.8,
    requiredDate: 'Today, Immediate',
    additionalNotes: 'Urgent requirement for surgery in Trauma Center.',
    createdAt: '15 mins ago',
    status: 'Active',
  },
  {
    id: 'req-102',
    patientName: 'Emergency Recipient #389',
    hospitalName: 'St. Jude Medical Center',
    city: 'East Wing Campus',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'High',
    distanceKm: 5.2,
    requiredDate: 'Tomorrow Morning',
    additionalNotes: 'Dengue patient with dropping platelet count.',
    createdAt: '1 hour ago',
    status: 'Active',
  },
  {
    id: 'req-103',
    patientName: 'Recipient #274',
    hospitalName: 'Metro General Hospital',
    city: 'Central District',
    bloodGroup: 'O-',
    unitsNeeded: 3,
    urgency: 'Normal',
    distanceKm: 8.1,
    requiredDate: 'In 2 days',
    additionalNotes: 'Scheduled procedure blood standby.',
    createdAt: '3 hours ago',
    status: 'Active',
  },
];

export const MOCK_DONOR_STATS = {
  nearbyActiveCount: 3,
  acceptedCount: 1,
  completedDonations: 4,
  responseRate: '94%',
};

export const MOCK_DONOR_HISTORY = [
  {
    id: 'req-201',
    hospitalName: 'St. Mary Trauma Hospital',
    city: 'North Sector, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    status: 'Completed',
    responseDate: '12 Sep 2026',
    notes: '2 units donated successfully at Trauma ICU.',
  },
  {
    id: 'req-198',
    hospitalName: 'City Care Hospital',
    city: 'Sector 14, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'High',
    status: 'Accepted',
    responseDate: '25 Sep 2026',
    notes: 'Accepted. Hospital coordinator contact active.',
  },
  {
    id: 'req-185',
    hospitalName: 'Apex Health Institute',
    city: 'West District',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Normal',
    status: 'Declined',
    responseDate: '02 Aug 2026',
    notes: 'Declined due to travel unavailability.',
  },
  {
    id: 'req-172',
    hospitalName: 'Metro General Hospital',
    city: 'Central District',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'Emergency',
    status: 'Cancelled',
    responseDate: '15 Jul 2026',
    notes: 'Request cancelled by recipient (fulfilled locally).',
  },
];

export const MOCK_RECIPIENT_REQUESTS = [
  {
    id: 'req-301',
    hospitalName: 'City General Hospital',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    status: 'Donor Accepted',
    donorResponsesCount: 2,
    acceptedDonors: [
      { name: 'David Miller', phone: '+1 (555) 123-9876', bloodGroup: 'A+', distanceKm: 2.4 },
      { name: 'Elena Rostova', phone: '+1 (555) 876-5432', bloodGroup: 'A+', distanceKm: 4.1 },
    ],
    requiredDate: 'Today, Immediate',
    createdAt: '25 mins ago',
  },
  {
    id: 'req-302',
    hospitalName: 'Memorial Trauma Center',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 1,
    urgency: 'High',
    status: 'Active',
    donorResponsesCount: 0,
    acceptedDonors: [],
    requiredDate: 'Tomorrow Morning',
    createdAt: '2 hours ago',
  },
];

export const MOCK_RECIPIENT_STATS = {
  totalRequests: 4,
  activeRequests: 2,
  donorsResponded: 2,
  fulfilledCount: 2,
};

export const MOCK_RECIPIENT_LOCATION = {
  lat: 40.7128,
  lng: -74.006,
  address: 'New York Central Search Center',
};

export const MOCK_SEARCHABLE_DONORS = [
  {
    id: 'donor-1',
    name: 'David M.',
    bloodGroup: 'A+',
    distanceKm: 2.4,
    city: 'New York, Sector 14',
    isAvailable: true,
    lastActive: '5 mins ago',
    donationsCompleted: 6,
    responseRate: '98%',
    lat: 40.725,
    lng: -73.998,
  },
  {
    id: 'donor-2',
    name: 'Elena R.',
    bloodGroup: 'A+',
    distanceKm: 4.1,
    city: 'New York, East Wing',
    isAvailable: true,
    lastActive: '12 mins ago',
    donationsCompleted: 4,
    responseRate: '92%',
    lat: 40.738,
    lng: -73.985,
  },
  {
    id: 'donor-3',
    name: 'Marcus Vance',
    bloodGroup: 'O-',
    distanceKm: 1.8,
    city: 'New York, Downtown',
    isAvailable: true,
    lastActive: 'Just now',
    donationsCompleted: 12,
    responseRate: '100%',
    lat: 40.708,
    lng: -74.012,
  },
  {
    id: 'donor-4',
    name: 'Sarah K.',
    bloodGroup: 'O+',
    distanceKm: 5.8,
    city: 'New York, Midtown',
    isAvailable: true,
    lastActive: '45 mins ago',
    donationsCompleted: 3,
    responseRate: '88%',
    lat: 40.752,
    lng: -73.977,
  },
  {
    id: 'donor-5',
    name: 'Robert T.',
    bloodGroup: 'B+',
    distanceKm: 6.9,
    city: 'New York, West District',
    isAvailable: true,
    lastActive: '1 hour ago',
    donationsCompleted: 5,
    responseRate: '95%',
    lat: 40.735,
    lng: -74.032,
  },
  {
    id: 'donor-6',
    name: 'Anita Patel',
    bloodGroup: 'AB+',
    distanceKm: 8.4,
    city: 'New York, North Campus',
    isAvailable: false,
    lastActive: '3 hours ago',
    donationsCompleted: 2,
    responseRate: '80%',
    lat: 40.768,
    lng: -73.962,
  },
  {
    id: 'donor-7',
    name: 'Jonathan L.',
    bloodGroup: 'A-',
    distanceKm: 12.1,
    city: 'New York, Queens Area',
    isAvailable: true,
    lastActive: '20 mins ago',
    donationsCompleted: 7,
    responseRate: '96%',
    lat: 40.748,
    lng: -73.912,
  },
  {
    id: 'donor-8',
    name: 'Sophia W.',
    bloodGroup: 'B-',
    distanceKm: 16.5,
    city: 'New York, Brooklyn Sector',
    isAvailable: true,
    lastActive: '2 hours ago',
    donationsCompleted: 1,
    responseRate: '90%',
    lat: 40.672,
    lng: -73.952,
  },
];

export const MOCK_ADMIN_STATS = {
  totalDonors: 142,
  totalRecipients: 89,
  activeAvailableDonors: 94,
  activeRequests: 8,
  emergencyRequests: 3,
  fulfilledRequests: 56,
};

export const MOCK_ADMIN_ACTIVITY = [
  {
    id: 'act-1',
    user: 'System Admin',
    action: 'Verified Donor Account #donor-3 (Marcus Vance)',
    time: '10 mins ago',
    type: 'security',
  },
  {
    id: 'act-2',
    user: 'Recipient #rec-12',
    action: 'Issued Emergency Request #req-301 (A+)',
    time: '25 mins ago',
    type: 'request',
  },
  {
    id: 'act-3',
    user: 'Donor #donor-1',
    action: 'Accepted Emergency Request #req-301',
    time: '20 mins ago',
    type: 'donor',
  },
  {
    id: 'act-4',
    user: 'System Admin',
    action: 'Logged System Audit Trail #audit-994',
    time: '1 hour ago',
    type: 'audit',
  },
];

export const MOCK_ADMIN_DONORS_LIST = [
  {
    id: 'donor-101',
    fullName: 'David Miller',
    email: 'david.m@example.com',
    phone: '+1 (555) 123-9876',
    bloodGroup: 'A+',
    city: 'New York',
    isAvailable: true,
    accountStatus: 'Active',
    joinedDate: '10 Jan 2026',
    donationsCompleted: 6,
  },
  {
    id: 'donor-102',
    fullName: 'Elena Rostova',
    email: 'elena.r@example.com',
    phone: '+1 (555) 876-5432',
    bloodGroup: 'A+',
    city: 'New York',
    isAvailable: true,
    accountStatus: 'Active',
    joinedDate: '15 Feb 2026',
    donationsCompleted: 4,
  },
  {
    id: 'donor-103',
    fullName: 'Marcus Vance',
    email: 'marcus.v@example.com',
    phone: '+1 (555) 345-6789',
    bloodGroup: 'O-',
    city: 'New York',
    isAvailable: true,
    accountStatus: 'Active',
    joinedDate: '01 Dec 2025',
    donationsCompleted: 12,
  },
  {
    id: 'donor-104',
    fullName: 'Sarah Jenkins',
    email: 'sarah.j@example.com',
    phone: '+1 (555) 456-7890',
    bloodGroup: 'O+',
    city: 'New York',
    isAvailable: false,
    accountStatus: 'Active',
    joinedDate: '20 Mar 2026',
    donationsCompleted: 3,
  },
  {
    id: 'donor-105',
    fullName: 'Robert Taylor',
    email: 'robert.t@example.com',
    phone: '+1 (555) 567-8901',
    bloodGroup: 'B+',
    city: 'Chicago',
    isAvailable: false,
    accountStatus: 'Blocked',
    joinedDate: '05 Apr 2026',
    donationsCompleted: 0,
  },
];

export const MOCK_ADMIN_RECIPIENTS_LIST = [
  {
    id: 'rec-201',
    fullName: 'Sarah Chen',
    email: 'recipient@bloodward.com',
    phone: '+1 (555) 987-6543',
    city: 'New York',
    accountStatus: 'Active',
    joinedDate: '02 Feb 2026',
    totalRequestsIssued: 4,
  },
  {
    id: 'rec-202',
    fullName: 'Michael Sterling',
    email: 'm.sterling@example.com',
    phone: '+1 (555) 234-8765',
    city: 'New York',
    accountStatus: 'Active',
    joinedDate: '18 Feb 2026',
    totalRequestsIssued: 2,
  },
  {
    id: 'rec-203',
    fullName: 'Amanda Hayes',
    email: 'amanda.h@example.com',
    phone: '+1 (555) 345-9876',
    city: 'Chicago',
    accountStatus: 'Active',
    joinedDate: '10 Mar 2026',
    totalRequestsIssued: 1,
  },
  {
    id: 'rec-204',
    fullName: 'Victor Krum',
    email: 'victor.k@example.com',
    phone: '+1 (555) 456-0987',
    city: 'Boston',
    accountStatus: 'Blocked',
    joinedDate: '22 Apr 2026',
    joinedDate: '22 Apr 2026',
    totalRequestsIssued: 0,
  },
];

export const MOCK_ADMIN_REQUESTS_LIST = [
  {
    id: 'req-301',
    recipientName: 'Sarah Chen',
    hospitalName: 'City General Hospital',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    status: 'Donor Accepted',
    donorResponsesCount: 2,
    createdAt: '25 mins ago',
    requiredDate: 'Today, Immediate',
    additionalNotes: 'Urgent surgery blood standby.',
  },
  {
    id: 'req-302',
    recipientName: 'Michael Sterling',
    hospitalName: 'Memorial Trauma Center',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 1,
    urgency: 'High',
    status: 'Active',
    donorResponsesCount: 0,
    createdAt: '2 hours ago',
    requiredDate: 'Tomorrow Morning',
    additionalNotes: 'Dengue platelet count drops.',
  },
  {
    id: 'req-303',
    recipientName: 'Amanda Hayes',
    hospitalName: 'St. Mary Hospital',
    city: 'Chicago',
    bloodGroup: 'O-',
    unitsNeeded: 3,
    urgency: 'Normal',
    status: 'Fulfilled',
    donorResponsesCount: 3,
    createdAt: '1 day ago',
    requiredDate: '28 Sep 2026',
    additionalNotes: 'Procedure completed.',
  },
  {
    id: 'req-304',
    recipientName: 'Suspicious User Account',
    hospitalName: 'Unverified Clinic #99',
    city: 'Unknown Area',
    bloodGroup: 'AB-',
    unitsNeeded: 10,
    urgency: 'Emergency',
    status: 'Active',
    donorResponsesCount: 0,
    createdAt: '3 hours ago',
    requiredDate: 'Immediate',
    additionalNotes: 'Unusually high units requested without hospital verification.',
  },
];

export const MOCK_AUDIT_LOGS_FULL = [
  {
    id: 'log-1001',
    timestamp: '02 Oct 2026, 07:30:15',
    actor: 'System Admin (admin@bloodward.com)',
    action: 'BLOCKED_USER_ACCOUNT',
    category: 'SECURITY',
    target: 'User: Robert Taylor (#donor-105)',
    ipAddress: '192.168.1.45',
    severity: 'HIGH',
    details: 'Account blocked due to multiple invalid contact verification attempts.',
  },
  {
    id: 'log-1002',
    timestamp: '02 Oct 2026, 06:45:22',
    actor: 'System Admin (admin@bloodward.com)',
    action: 'CANCELLED_SUSPICIOUS_REQUEST',
    category: 'REQUEST_MGMT',
    target: 'Blood Request #req-304',
    ipAddress: '192.168.1.45',
    severity: 'HIGH',
    details: 'Broadcast cancelled: Unusually high 10 units requested without clinic verification.',
  },
  {
    id: 'log-1003',
    timestamp: '01 Oct 2026, 18:20:10',
    actor: 'Recipient: Sarah Chen (#rec-201)',
    action: 'CREATED_EMERGENCY_REQUEST',
    category: 'REQUEST_MGMT',
    target: 'Blood Request #req-301 (A+)',
    ipAddress: '172.56.21.88',
    severity: 'NORMAL',
    details: 'Emergency blood request published to 4 nearby matching donors in New York.',
  },
  {
    id: 'log-1004',
    timestamp: '01 Oct 2026, 15:10:04',
    actor: 'Donor: David Miller (#donor-101)',
    action: 'ACCEPTED_BLOOD_REQUEST',
    category: 'DONOR_ACTION',
    target: 'Blood Request #req-301',
    ipAddress: '108.162.2.14',
    severity: 'NORMAL',
    details: 'Donor accepted emergency request. Phone contact unlocked to recipient.',
  },
  {
    id: 'log-1005',
    timestamp: '30 Sep 2026, 12:00:00',
    actor: 'System Security Subsystem',
    action: 'SYSTEM_POLICY_AUDIT',
    category: 'SYSTEM',
    target: 'Global Auth Config',
    ipAddress: '127.0.0.1 (Localhost)',
    severity: 'LOW',
    details: 'HttpOnly cookie session integrity audit passed. Zero localStorage token leaks detected.',
  },
];