export const MOCK_DONOR_REQUESTS = [
  {
    id: 'req-101',
    patientName: 'Emergency Recipient #402',
    hospitalName: 'City Care Hospital',
    city: 'Sector 14, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    distanceKm: 2.8,
    requiredDate: 'Today, Immediate',
    additionalNotes: 'Urgent requirement for surgery in Trauma Center.',
    createdAt: '15 mins ago',
    status: 'Active',
  },
  {
    id: 'req-102',
    patientName: 'Emergency Recipient #389',
    hospitalName: 'St. Jude Medical Center',
    city: 'East Wing Campus',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'High',
    distanceKm: 5.2,
    requiredDate: 'Tomorrow Morning',
    additionalNotes: 'Dengue patient with dropping platelet count.',
    createdAt: '1 hour ago',
    status: 'Active',
  },
  {
    id: 'req-103',
    patientName: 'Recipient #274',
    hospitalName: 'Metro General Hospital',
    city: 'Central District',
    bloodGroup: 'O-',
    unitsNeeded: 3,
    urgency: 'Normal',
    distanceKm: 8.1,
    requiredDate: 'In 2 days',
    additionalNotes: 'Scheduled procedure blood standby.',
    createdAt: '3 hours ago',
    status: 'Active',
  },
];

export const MOCK_DONOR_STATS = {
  nearbyActiveCount: 3,
  acceptedCount: 1,
  completedDonations: 4,
  responseRate: '94%',
};

export const MOCK_DONOR_HISTORY = [
  {
    id: 'req-201',
    hospitalName: 'St. Mary Trauma Hospital',
    city: 'North Sector, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    status: 'Completed',
    responseDate: '12 Sep 2026',
    notes: '2 units donated successfully at Trauma ICU.',
  },
  {
    id: 'req-198',
    hospitalName: 'City Care Hospital',
    city: 'Sector 14, Main City',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'High',
    status: 'Accepted',
    responseDate: '25 Sep 2026',
    notes: 'Accepted. Hospital coordinator contact active.',
  },
  {
    id: 'req-185',
    hospitalName: 'Apex Health Institute',
    city: 'West District',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    urgency: 'Normal',
    status: 'Declined',
    responseDate: '02 Aug 2026',
    notes: 'Declined due to travel unavailability.',
  },
  {
    id: 'req-172',
    hospitalName: 'Metro General Hospital',
    city: 'Central District',
    bloodGroup: 'O+',
    unitsNeeded: 1,
    urgency: 'Emergency',
    status: 'Cancelled',
    responseDate: '15 Jul 2026',
    notes: 'Request cancelled by recipient (fulfilled locally).',
  },
];

export const MOCK_RECIPIENT_REQUESTS = [
  {
    id: 'req-301',
    hospitalName: 'City General Hospital',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 2,
    urgency: 'Emergency',
    status: 'Donor Accepted',
    donorResponsesCount: 2,
    acceptedDonors: [
      { name: 'David Miller', phone: '+1 (555) 123-9876', bloodGroup: 'A+', distanceKm: 2.4 },
      { name: 'Elena Rostova', phone: '+1 (555) 876-5432', bloodGroup: 'A+', distanceKm: 4.1 },
    ],
    requiredDate: 'Today, Immediate',
    createdAt: '25 mins ago',
  },
  {
    id: 'req-302',
    hospitalName: 'Memorial Trauma Center',
    city: 'New York',
    bloodGroup: 'A+',
    unitsNeeded: 1,
    urgency: 'High',
    status: 'Active',
    donorResponsesCount: 0,
    acceptedDonors: [],
    requiredDate: 'Tomorrow Morning',
    createdAt: '2 hours ago',
  },
];

export const MOCK_RECIPIENT_STATS = {
  totalRequests: 4,
  activeRequests: 2,
  donorsResponded: 2,
  fulfilledCount: 2,
};